# Generated by Django 4.2 on 2023-04-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_profile_picture_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_chatting',
            field=models.BooleanField(default=False, verbose_name='Is Chatting'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture', verbose_name='Profile_Picture'),
        ),
    ]
