# Generated by Django 4.2 on 2023-04-17 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_room_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User1', to=settings.AUTH_USER_MODEL, verbose_name='User 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='user_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User2', to=settings.AUTH_USER_MODEL, verbose_name='User 2'),
            preserve_default=False,
        ),
    ]
